name: Deploy documentation and package
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r quality.txt
          pip install -r requirements.txt

      - name: Release to pypi with poetry
        run: |
          poetry config pypi-token.pypi ${{ secrets.MCHPLNET_PYPI }}
          poetry publish -vvv --build


